package it.gestionechiavi.mezzi
import android.content.*
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import org.json.*
class MainActivity:AppCompatActivity(){
 private lateinit var prefs:android.content.SharedPreferences; private var currentAssignment:String?=null; private var habitualPlate=""; private var initialPhotoRequired=false
 private val scanLauncher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==RESULT_OK)r.data?.getStringExtra("qr")?.let{submitScan(it)}}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);prefs=getSharedPreferences("device",MODE_PRIVATE);findViewById<Button>(R.id.scan).setOnClickListener{if(token().isBlank())Toast.makeText(this,"Dispositivo non associato. Accedi come responsabile per associarlo.",Toast.LENGTH_LONG).show()else scanLauncher.launch(Intent(this,ScannerActivity::class.java))};findViewById<Button>(R.id.photo).setOnClickListener{startActivity(Intent(this,PhotoActivity::class.java).putExtra("assignment_id",currentAssignment).putExtra("driver_code",prefs.getInt("driver",0)).putExtra("device_token",token()).putExtra("initial_habitual",initialPhotoRequired&&currentAssignment==null).putExtra("plate",habitualPlate))};findViewById<Button>(R.id.changeDriver).setOnClickListener{startActivity(Intent(this,ManagerActivity::class.java))};findViewById<Spinner>(R.id.driverSpinner).visibility=View.GONE;findViewById<Button>(R.id.saveDriver).visibility=View.GONE;render();refresh()}
 private fun token()=prefs.getString("device_token","").orEmpty()
 private fun render(){val c=prefs.getInt("driver",0);findViewById<TextView>(R.id.driver).text=if(token().isBlank())"Dispositivo non associato" else "Autista: ${prefs.getString("driver_name","")} · ${prefs.getString("driver_label",c.toString())}";findViewById<TextView>(R.id.message).text=if(token().isBlank())"Un responsabile deve associare questo telefono a un autista." else ""}
 private fun refresh(){val t=token();if(t.isBlank())return;Api.get("/device-me",t){status,s->runOnUiThread{if(status==401){prefs.edit().clear().apply();render();return@runOnUiThread};if(status !in 200..299){findViewById<TextView>(R.id.message).text="Errore collegamento dispositivo ($status)";return@runOnUiThread};val d=runCatching{JSONObject(s).getJSONObject("driver")}.getOrNull();if(d!=null){val code=d.optInt("code");val name=d.optString("name");val raw=if(d.isNull("code_label"))"" else d.optString("code_label").trim();val label=raw.takeUnless{it.isBlank()||it.equals("null",true)}?:code.toString();habitualPlate=d.optString("habitual_plate").takeUnless{it.equals("null",true)}.orEmpty();initialPhotoRequired=d.optBoolean("initial_photo_required",false);prefs.edit().putInt("driver",code).putString("driver_name",name).putString("driver_label",label).apply();render()};loadAssignment(t)}}}
 private fun loadAssignment(t:String){Api.get("/assignment-current",t){status,s->runOnUiThread{if(status !in 200..299)return@runOnUiThread;val o=if(s.trim()=="null")null else runCatching{JSONObject(s)}.getOrNull();if(o==null||!o.has("id")){currentAssignment=null;if(initialPhotoRequired&&habitualPlate.isNotBlank()){findViewById<TextView>(R.id.status).text="Furgone abituale: $habitualPlate · foto iniziali richieste";findViewById<Button>(R.id.photo).apply{visibility=View.VISIBLE;text="FOTO INIZIALI FURGONE"}}else{findViewById<TextView>(R.id.status).text="Nessuna chiave assegnata";findViewById<Button>(R.id.photo).visibility=View.GONE}}else{currentAssignment=o.optString("id");findViewById<TextView>(R.id.status).text="Chiave assegnata: ${o.optString("plate")}";findViewById<Button>(R.id.photo).apply{visibility=if(o.optBoolean("changed_vehicle",false))View.VISIBLE else View.GONE;text="FOTO STATO MEZZO"}}}}}
 private fun submitScan(q:String){Api.postJson("/scan",JSONObject().put("qr_code",q),token()){c,s->runOnUiThread{val o=runCatching{JSONObject(s)}.getOrNull();findViewById<TextView>(R.id.message).text=if(c in 200..299)if(o?.optString("action")=="returned")"Chiave restituita" else "Chiave assegnata" else o?.optString("error","Errore $c")?:"Errore $c";refresh()}}}
 override fun onResume(){super.onResume();if(::prefs.isInitialized){render();refresh()}}
}