package it.gestionechiavi.mezzi
import android.app.*;import android.content.*;import android.os.Bundle;import android.widget.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import org.json.*
data class Driver(val code:Int,val name:String,val label:String){override fun toString()="$name · $label"}
class MainActivity:AppCompatActivity(){private lateinit var prefs:android.content.SharedPreferences;private var drivers=listOf<Driver>();private var currentAssignment:String?=null;private val scanLauncher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==RESULT_OK)r.data?.getStringExtra("qr")?.let{submitScan(it)}}
override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);prefs=getSharedPreferences("device",MODE_PRIVATE);findViewById<Button>(R.id.scan).setOnClickListener{if(prefs.getInt("driver",0)==0)Toast.makeText(this,"Prima associa l'autista",Toast.LENGTH_SHORT).show()else scanLauncher.launch(Intent(this,ScannerActivity::class.java))};findViewById<Button>(R.id.saveDriver).setOnClickListener{val d=drivers.getOrNull(findViewById<Spinner>(R.id.driverSpinner).selectedItemPosition)?:return@setOnClickListener;prefs.edit().putInt("driver",d.code).putString("driver_name",d.name).putString("driver_label",d.label).apply();render();refresh()};findViewById<Button>(R.id.photo).setOnClickListener{startActivity(Intent(this,PhotoActivity::class.java).putExtra("assignment_id",currentAssignment).putExtra("driver_code",prefs.getInt("driver",0)))};findViewById<Button>(R.id.changeDriver).setOnClickListener{val e=EditText(this);e.inputType=2;AlertDialog.Builder(this).setTitle("Autorizzazione responsabile").setView(e).setPositiveButton("Verifica"){_,_->verify(e.text.toString())}.setNegativeButton("Annulla",null).show()};load()}
private fun load(){Api.get("/drivers"){c,s->runOnUiThread{if(c !in 200..299)return@runOnUiThread;val a=JSONArray(s);drivers=(0 until a.length()).map{val o=a.getJSONObject(it);val code=o.getInt("code");Driver(code,o.getString("name"),if(o.isNull("code_label"))code.toString()else o.optString("code_label",code.toString()))};findViewById<Spinner>(R.id.driverSpinner).adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,drivers);render();refresh()}}}
private fun render(){val c=prefs.getInt("driver",0);findViewById<TextView>(R.id.driver).text=if(c==0)"Autista non configurato"else"Autista: ${prefs.getString("driver_name","")} · ${prefs.getString("driver_label",c.toString())}";findViewById<Spinner>(R.id.driverSpinner).visibility=if(c==0)android.view.View.VISIBLE else android.view.View.GONE;findViewById<Button>(R.id.saveDriver).visibility=if(c==0)android.view.View.VISIBLE else android.view.View.GONE}
private fun refresh(){val c=prefs.getInt("driver",0);if(c==0)return;Api.get("/assignment-current?driver_code=$c"){status,s->runOnUiThread{if(status !in 200..299)return@runOnUiThread;val o=runCatching{JSONObject(s)}.getOrNull();if(o==null||!o.has("id")){currentAssignment=null;findViewById<TextView>(R.id.status).text="Nessuna chiave assegnata";findViewById<Button>(R.id.photo).visibility=android.view.View.GONE}else{currentAssignment=o.getString("id");findViewById<TextView>(R.id.status).text="Chiave assegnata: ${o.optString("plate")}";findViewById<Button>(R.id.photo).visibility=if(o.optBoolean("changed_vehicle",false))android.view.View.VISIBLE else android.view.View.GONE}}}}
private fun submitScan(q:String){Api.postJson("/scan",JSONObject().put("driver_code",prefs.getInt("driver",0)).put("qr_code",q)){_,s->runOnUiThread{val o=runCatching{JSONObject(s)}.getOrNull();findViewById<TextView>(R.id.message).text=o?.optString("message",o.optString("error","Operazione completata"))?:"Errore";refresh()}}};private fun verify(pin:String){Api.postJson("/manager-login",JSONObject().put("pin",pin)){c,_->runOnUiThread{if(c in 200..299){prefs.edit().clear().apply();render()}else findViewById<TextView>(R.id.message).text="Codice responsabile non valido"}}};override fun onResume(){super.onResume();if(::prefs.isInitialized)refresh()}}
