package it.gestionechiavi.mezzi
import android.os.Bundle
import android.text.InputType
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.*
class ManagerActivity:AppCompatActivity(){
 private lateinit var root:LinearLayout;private var manager="";private var managerToken="";private var drivers=JSONArray()
 override fun onCreate(b:Bundle?){super.onCreate(b);root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(40,100,40,40)};setContentView(ScrollView(this).apply{addView(root)});showLogin()}
 private fun tv(s:String,z:Float=18f)=TextView(this).apply{text=s;textSize=z;setPadding(0,12,0,12)}
 private fun input(h:String,p:Boolean=false)=EditText(this).apply{hint=h;if(p)inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_VARIATION_PASSWORD}
 private fun btn(s:String,f:()->Unit)=Button(this).apply{text=s;isAllCaps=false;setOnClickListener{f()}}
 private fun showLogin(){root.removeAllViews();root.addView(tv("GESTIONE FLOTTA",12f));root.addView(tv("Area Responsabile",30f));root.addView(tv("Usa il tuo nome e PIN personale."));val n=input("Nome responsabile");val p=input("PIN",true);val m=tv("");root.addView(n);root.addView(p);root.addView(btn("Accedi"){Api.postJson("/manager-login",JSONObject().put("name",n.text.toString().trim()).put("pin",p.text.toString().trim())){c,s->runOnUiThread{if(c in 200..299){val o=JSONObject(s);manager=o.optString("name");managerToken=o.optString("token");showDashboard()}else m.text=runCatching{JSONObject(s).optString("error")}.getOrDefault("Accesso non riuscito")}}}});root.addView(m);root.addView(btn("Torna ad autista"){finish()})}
 private fun showDashboard(){root.removeAllViews();root.addView(tv("Area Responsabile",30f));root.addView(tv("Responsabile: $manager"));val status=tv("Caricamento dashboard…");root.addView(status);Api.get("/manager-dashboard",managerToken){c,s->runOnUiThread{status.text=if(c in 200..299){val st=JSONObject(s).optJSONObject("stats");"Chiavi assegnate: ${st?.optInt("assigned",0)} · Disponibili: ${st?.optInt("available",0)} · Autisti: ${st?.optInt("drivers",0)}"}else"Dashboard non disponibile ($c)"}};root.addView(tv("Associa questo dispositivo",22f));root.addView(tv("Seleziona l'autista che userà permanentemente questo telefono. Una nuova associazione sostituisce quella precedente per lo stesso autista."));val sp=Spinner(this);val feedback=tv("");root.addView(sp);Api.get("/manager-habitual",managerToken){c,s->runOnUiThread{if(c in 200..299){drivers=JSONObject(s).optJSONArray("drivers")?:JSONArray();val names=(0 until drivers.length()).map{i->val d=drivers.getJSONObject(i);val code=d.optInt("code");val label=d.optString("code_label").ifBlank{code.toString()};"${d.optString("name")} · $label"};sp.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names)}else feedback.text="Impossibile caricare autisti ($c)"}};root.addView(btn("Associa telefono all'autista"){if(drivers.length()==0)return@btn;val d=drivers.getJSONObject(sp.selectedItemPosition);Api.postJson("/device-register",JSONObject().put("driver_code",d.optInt("code")).put("device_label",android.os.Build.MANUFACTURER+" "+android.os.Build.MODEL),managerToken){c,s->runOnUiThread{if(c in 200..299){val o=JSONObject(s);val dr=o.getJSONObject("driver");val code=dr.optInt("code");val label=dr.optString("code_label").ifBlank{code.toString()};getSharedPreferences("device",MODE_PRIVATE).edit().putString("device_token",o.getString("device_token")).putInt("driver",code).putString("driver_name",dr.optString("name")).putString("driver_label",label).apply();feedback.text="Dispositivo associato a ${dr.optString("name")}"}else feedback.text=runCatching{JSONObject(s).optString("error")}.getOrDefault("Associazione non riuscita")}}}});root.addView(feedback);root.addView(btn("Torna ad autista"){finish()});root.addView(btn("Esci area responsabile"){manager="";managerToken="";showLogin()})}
}